export const dummyProducts = [
  {
    id: "dummy-1",
    name: "Nasi Padang Rendang Spesial",
    description: "Nasi Padang autentik dengan rendang daging sapi empuk, gulai nangka, daun singkong, sambal hijau, dan bumbu rendang ekstra.",
    price: 35000,
    imageUrl: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&h=600&fit=crop",
    minQty: 30,
    currentQty: 15,
    deadlineDate: new Date(Date.now() + 2 * 86400000),
    status: "active" as const,
    sellerId: "dummy-seller-1",
    sellerName: "Dapur Minang",
    storeName: "Dapur Minang",
    storeAddress: "Jakarta Selatan",
    sellerAddress: "Jakarta Selatan",
    sellerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop"
  },
  {
    id: "dummy-2",
    name: "Sate Ayam Madura Bumbu Kacang",
    description: "10 tusuk sate ayam Madura asli dengan bumbu kacang kental, kecap manis, irisan bawang merah, dan cabai rawit.",
    price: 25000,
    imageUrl: "https://images.unsplash.com/photo-1628294895950-9805252327bc?w=800&h=600&fit=crop",
    minQty: 50,
    currentQty: 45,
    deadlineDate: new Date(Date.now() + 1 * 86400000),
    status: "active" as const,
    sellerId: "dummy-seller-2",
    sellerName: "Sate Cak Udin",
    storeName: "Sate Cak Udin",
    storeAddress: "Jakarta Timur",
    sellerAddress: "Jakarta Timur",
    sellerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop"
  },
  {
    id: "dummy-3",
    name: "Bakso Urat Wonogiri",
    description: "Bakso sapi asli dengan tambahan urat kenyal, dilengkapi dengan mie kuning, bihun, sawi, dan kuah kaldu sapi yang gurih.",
    price: 20000,
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&h=600&fit=crop",
    minQty: 40,
    currentQty: 40,
    deadlineDate: new Date(Date.now() + 3 * 86400000),
    status: "active" as const,
    sellerId: "dummy-seller-3",
    sellerName: "Bakso Mas Kumis",
    storeName: "Bakso Mas Kumis",
    storeAddress: "Depok",
    sellerAddress: "Depok",
    sellerAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop"
  },
  {
    id: "dummy-4",
    name: "Mie Ayam Pangsit Mangkuk Pangsit",
    description: "Mie ayam lezat disajikan di dalam mangkuk pangsit goreng renyah, lengkap dengan potongan ayam cincang, sayur, dan kuah terpisah.",
    price: 22000,
    imageUrl: "https://images.unsplash.com/photo-1555126634-323283e090fa?w=800&h=600&fit=crop",
    minQty: 25,
    currentQty: 10,
    deadlineDate: new Date(Date.now() + 4 * 86400000),
    status: "active" as const,
    sellerId: "dummy-seller-4",
    sellerName: "Mie Ayam Berkah",
    storeName: "Mie Ayam Berkah",
    storeAddress: "Tangerang",
    sellerAddress: "Tangerang",
    sellerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop"
  },
  {
    id: "dummy-5",
    name: "Ayam Geprek Sambal Bawang Ekstra Pedas",
    description: "Ayam goreng tepung krispi digeprek hancur dengan ulekan sambal bawang segar yang pedasnya nendang. Sudah termasuk nasi.",
    price: 18000,
    imageUrl: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&h=600&fit=crop",
    minQty: 60,
    currentQty: 55,
    deadlineDate: new Date(Date.now() + 2 * 86400000),
    status: "active" as const,
    sellerId: "dummy-seller-5",
    sellerName: "Geprek Jontor",
    storeName: "Geprek Jontor",
    storeAddress: "Jakarta Barat",
    sellerAddress: "Jakarta Barat",
    sellerAvatar: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=100&h=100&fit=crop"
  },
  {
    id: "dummy-6",
    name: "Nasi Goreng Spesial Telur Dadar",
    description: "Nasi goreng kecap bumbu rempah dengan suwiran ayam, bakso sapi, sosis, dan telur dadar lebar menutupi nasi.",
    price: 25000,
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&h=600&fit=crop",
    minQty: 30,
    currentQty: 5,
    deadlineDate: new Date(Date.now() + 5 * 86400000),
    status: "active" as const,
    sellerId: "dummy-seller-6",
    sellerName: "Nasgor Gila 88",
    storeName: "Nasgor Gila 88",
    storeAddress: "Bogor",
    sellerAddress: "Bogor",
    sellerAvatar: "https://images.unsplash.com/photo-1528763380143-65b3ac89a3ff?w=100&h=100&fit=crop"
  },
  {
    id: "dummy-7",
    name: "Es Campur Sinar Garut",
    description: "Minuman segar berisi alpukat, kelapa muda, nangka, kolang-kaling, cincau hitam, disiram sirup merah muda dan susu kental manis.",
    price: 15000,
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&h=600&fit=crop",
    minQty: 50,
    currentQty: 20,
    deadlineDate: new Date(Date.now() + 2 * 86400000),
    status: "active" as const,
    sellerId: "dummy-seller-7",
    sellerName: "Es Campur Segar",
    storeName: "Es Campur Segar",
    storeAddress: "Jakarta Utara",
    sellerAddress: "Jakarta Utara",
    sellerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop"
  },
  {
    id: "dummy-8",
    name: "Martabak Manis Coklat Keju",
    description: "Martabak manis (terang bulan) tebal dan empuk, dengan isian melimpah meses coklat ceres dan parutan keju kraft.",
    price: 45000,
    imageUrl: "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&h=600&fit=crop",
    minQty: 20,
    currentQty: 18,
    deadlineDate: new Date(Date.now() + 1 * 86400000),
    status: "active" as const,
    sellerId: "dummy-seller-8",
    sellerName: "Martabak Boss",
    storeName: "Martabak Boss",
    storeAddress: "Bekasi",
    sellerAddress: "Bekasi",
    sellerAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop"
  },
  {
    id: "dummy-9",
    name: "Pempek Kapal Selam Palembang Asli",
    description: "Pempek ukuran besar berisi telur bebek utuh, digoreng garing di luar dan lembut di dalam. Disajikan dengan cuko kental pedas manis.",
    price: 25000,
    imageUrl: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=800&h=600&fit=crop",
    minQty: 40,
    currentQty: 12,
    deadlineDate: new Date(Date.now() + 3 * 86400000),
    status: "active" as const,
    sellerId: "dummy-seller-9",
    sellerName: "Pempek Wong Kito",
    storeName: "Pempek Wong Kito",
    storeAddress: "Tangerang Selatan",
    sellerAddress: "Tangerang Selatan",
    sellerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop"
  },
  {
    id: "dummy-10",
    name: "Gado-gado Siram Bumbu Kacang",
    description: "Salad sayuran rebus khas Indonesia (bayam, kacang panjang, tauge, labu siam) dengan tahu, tempe, telur, disiram bumbu kacang legit.",
    price: 20000,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop",
    minQty: 35,
    currentQty: 30,
    deadlineDate: new Date(Date.now() + 2 * 86400000),
    status: "active" as const,
    sellerId: "dummy-seller-10",
    sellerName: "Gado-gado Boplo",
    storeName: "Gado-gado Boplo",
    storeAddress: "Jakarta Pusat",
    sellerAddress: "Jakarta Pusat",
    sellerAvatar: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=100&h=100&fit=crop"
  }
];
